# Generated by Django 4.2.10 on 2024-02-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uplaodphoto',
            name='description',
        ),
    ]
